name: GitHub Actions Push to DockerHub
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          registry: 'docker.io'
          image: 'lukamit/menu_api'
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: v1, latest
          docker_file: '.'
          buildArgs: MONGODB_USERNAME = ${{ secrets.MONGODB_USERNAME }},
            MONGODB_PASSWORD = ${{ secrets.MONGODB_PASSWORD }},
            NODE_ENV = 'github_action'
      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"
